name: pangogest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  animated_text_kit: ^4.2.2
  badges: ^3.1.2
  cached_network_image: ^3.4.0
  chatview: ^2.1.1
  cloud_firestore: ^5.4.4
  device_info_plus: ^11.0.0
  dropdown_button2: ^2.3.9
  easy_date_timeline: ^1.1.3
  file_picker: ^8.1.3
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.3
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  gap: ^3.0.1
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  http: ^1.2.2
  icons_plus: ^5.0.0
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0

dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
